[package]
edition.workspace = true
name = "longport-proto"
version.workspace = true
description = "LongPort Protocol"
license = "MIT OR Apache-2.0"

[dependencies]
prost.workspace = true
serde = { workspace = true, features = ["derive"] }
