[package]
edition = "2021"
name = "longport-proto"
version = "3.0.0"
description = "LongPort Protocol"
license = "MIT OR Apache-2.0"

[dependencies]
prost = "0.13.3"
serde = { version = "1.0.137", features = ["derive"] }
