name: Issue Notify
on:
  issues:
    types: [opened]

jobs:
  notify:
    runs-on: ubuntu-22.04
    steps:
      - name: Send GitHub Action data to a Slack workflow
        uses: slackapi/slack-github-action@v2.1.1
        with:
          webhook: ${{ secrets.SLACK_WEBHOOK_URL }}
          webhook-type: webhook-trigger
          payload: |
            text: |
              ${{ github.event.issue.title }} #${{ github.event.issue.number }}

              ${{ github.event.issue.html_url }}
            url: ${{ github.event.issue.html_url }}
